version: '3.8'

services:
  rstudio:
    build:
      context: environment/rstudio/
      dockerfile: Dockerfile
      network: "host"
    tty: true
    network_mode: "host"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/home/rstudio:cached
      - .:/workspace:cached
